install_data(
  'com.vandragt.sidewing.desktop',
  install_dir: get_option('datadir') / 'applications',
)

install_data(
  'com.vandragt.sidewing.metainfo.xml',
  install_dir: get_option('datadir') / 'metainfo',
)

install_data(
  'icons/hicolor/scalable/apps/com.vandragt.sidewing.svg',
  install_dir: get_option('datadir') / 'icons/hicolor/scalable/apps',
)
